name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/aws/cli@master
      - name: download cache
        with:
          args: "s3 cp s3://autoinstallinstallmacos-cache-bucket/cache.plist ./"
          secrets: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]

      - uses: actions/checkout@v1
      - name: run aaim.py
      - run: |
           sudo pip install xattr 
           sudo python ./autoinstallinstallmacos.py

      - uses: actions/aws/cli@master
      - name: upload cache
        with:
          args: "s3 cp ./.cache.plist s3://autoinstallinstallmacos-cache-bucket"
          secrets: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]


