name: CI

on: [push]

jobs:
  build:
    runs-on: macos-10.14

    steps:
     - uses: actions/checkout@v1
     - run: |
           sudo pip install xattr 
           sudo pip install awscli
           ls="$(aws s3 ls autoinstallinstallmacos-cache-bucket)"
           grep -q cache.plist <<< "$ls" && aws s3 cp s3://autoinstallinstallmacos-cache-bucket/cache.plist ./
           sudo python ./autoinstallinstallmacos.py > /dev/null 2>&1
           aws s3 cp ./.cache.plist s3://autoinstallinstallmacos-cache-bucket
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

