name: CI

on: [push]

jobs:
  build:
    runs-on: macos-10.14

    steps:
     - uses: actions/checkout@v1
     - run: |
           sudo pip3 install xattr 
           sudo pip3 install awscli
           ls="$(aws s3 ls autoinstallinstallmacs)"
           grep -q .cache.plist <<< "$ls" && aws s3 cp s3://autoinstallinstallmacos/.cache.plist ./
           sudo python3 ./autoinstallinstallmacos.py
           aws s3 sync ./content s3://autoinstallinstallmacos
           aws s3 cp ./.cache.plist s3://autoinstallinstallmacos
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

