name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: run aaim.py
        run: |
           sudo pip install xattr 
           sudo python ./autoinstallinstallmacos.py
      - uses: actions/upload-artifact@master
        with:
          name: cache.plist
          path: .cached_products
